# Generated by Django 5.0.3 on 2024-07-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_transaction_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='From',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.accountnumber'),
        ),
    ]
